# =========================================================
# SpaceCrop Database - Oracle Database Free 23c
# =========================================================

FROM gvenzl/oracle-free:23-slim

# O DDL será executado durante a inicialização do Oracle.
COPY docker/spacecrop_ddl.sql /container-entrypoint-initdb.d/01-spacecrop-ddl.sql

EXPOSE 1521