
FROM gvenzl/oracle-free:23-slim

COPY spacecrop_ddl.sql /container-entrypoint-initdb.d/01-spacecrop-ddl.sql
COPY db-entrypoint.sh /opt/oracle/db-entrypoint.sh

USER root
RUN chmod +x /opt/oracle/db-entrypoint.sh
USER oracle

EXPOSE 1521

ENTRYPOINT ["/opt/oracle/db-entrypoint.sh"]
